src/Entity/Code.php
<?php

namespace App\Entity;

use App\Repository\CodeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: codeRepository::class)]
class Code
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $code = null;

    #[ORM\Column(length: 255)]
    private ?string $reduction = null;

    #[ORM\Column(length: 255)]
    private ?string $date_debut = null;

    #[ORM\Column(length: 255)]
    private ?string $date_fin = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getReduction(): ?string
    {
        return $this->reduction;
    }

    public function setReduction(string $reduction): static
    {
        $this->reduction = $reduction;

        return $this;
    }

    public function getDateDebut(): ?string
    {
        return $this->date_debut;
    }

    public function setDateDebut(string $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?string
    {
        return $this->date_fin;
    }

    public function setDateFin(string $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }
}

src/Form/CodeType.php
<?php

namespace App\Form;

use App\Entity\Code;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CodeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('code')
            ->add('reduction')
            ->add('date_debut')
            ->add('date_fin')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Code::class,
        ]);
    }
}

src/Controller/CodeController.php
<?php

namespace App\Controller;

use App\Entity\Code;
use App\Form\CodeType;
use App\Repository\CodeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/code')]
class CodeController extends AbstractController
{
    #[Route('/', name: 'app_code_index', methods: ['GET'])]
    public function index(CodeRepository $codeRepository): Response
    {
        return $this->render('code/index.html.twig', [
            'codes' => $codeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_code_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $code = new Code();
        $form = $this->createForm(CodeType::class, $code);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($code);
            $entityManager->flush();

            return $this->redirectToRoute('app_code_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('code/new.html.twig', [
            'code' => $code,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_code_show', methods: ['GET'])]
    public function show(Code $code): Response
    {
        return $this->render('code/show.html.twig', [
            'code' => $code,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_code_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Code $code, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CodeType::class, $code);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_code_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('code/edit.html.twig', [
            'code' => $code,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_code_delete', methods: ['POST'])]
    public function delete(Request $request, Code $code, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$code->getId(), $request->request->get('_token'))) {
            $entityManager->remove($code);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_code_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/code/_delete_form.html.twig
<form method="post" action="{{ path('app_code_delete', {'id': code.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ code.id) }}">
    <button class="btn">Delete</button>
</form>

templates/code/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/code/edit.html.twig
{% extends 'back.html.twig' %}
{% block css %}
{{ parent() }}
{%endblock%}

{% block title %}code promo edit{% endblock %}
{% block navbar %}
{{ parent() }}
{%endblock%}

{% block body %}
{{ parent() }}
    <h1>Edit Code</h1>

    {{ include('code/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_code_index') }}">back to list</a>

    {{ include('code/_delete_form.html.twig') }}
{% endblock %}

templates/code/index.html.twig
{% extends 'back.html.twig' %}
{% block css %}
{{ parent() }}
{%endblock%}

{% block title %}code promo{% endblock %}
{% block navbar %}
{{ parent() }}
{%endblock%}

{% block body %}
{{ parent() }}
    <h1>Code index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Code</th>
                <th>Reduction</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for code in codes %}
            <tr>
                <td>{{ code.id }}</td>
                <td>{{ code.code }}</td>
                <td>{{ code.reduction }}</td>
                <td>{{ code.dateDebut }}</td>
                <td>{{ code.dateFin }}</td>
                <td>
                    <a href="{{ path('app_code_show', {'id': code.id}) }}">show</a>
                    <a href="{{ path('app_code_edit', {'id': code.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_code_new') }}">Create new</a>
{% endblock %}

templates/code/new.html.twig
{% extends 'back.html.twig' %}
{% block css %}
{{ parent() }}
{%endblock%}

{% block title %}code promo new{% endblock %}
{% block navbar %}
{{ parent() }}
{%endblock%}

{% block body %}
{{ parent() }}
    <h1>Create new Code</h1>

    {{ include('code/_form.html.twig') }}

    <a href="{{ path('app_code_index') }}">back to list</a>
{% endblock %}

templates/code/show.html.twig
{% extends 'back.html.twig' %}
{% block css %}
{{ parent() }}
{%endblock%}

{% block title %}code promo detail{% endblock %}
{% block navbar %}
{{ parent() }}
{%endblock%}

{% block body %}
{{ parent() }}
    <h1>Code</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ code.id }}</td>
            </tr>
            <tr>
                <th>Code</th>
                <td>{{ code.code }}</td>
            </tr>
            <tr>
                <th>Reduction</th>
                <td>{{ code.reduction }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ code.dateDebut }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ code.dateFin }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_code_index') }}">back to list</a>

    <a href="{{ path('app_code_edit', {'id': code.id}) }}">edit</a>

    {{ include('code/_delete_form.html.twig') }}
{% endblock %}